name: deploy

on:
  push:
    branches: master

env:
  SLUG: git-most-wanted

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        run: npm ci
      - name: build
        run: npx slidev build --base /talks/${{ env.SLUG }}
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist
      - name: deploy upstream
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.UPSTREAM_URL }}
          user: ${{ secrets.UPSTREAM_USERNAME }}
          password: ${{ secrets.UPSTREAM_PASSWORD }}
          localDir: dist
          remoteDir: htdocs/${{ secrets.APEX_DOMAIN_URI }}/${{ secrets.SUBDOMAIN_URI }}/talks/${{ env.SLUG }}
          options: "--delete"
